tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mdogan/zulu"
brew "automake"
brew "azure-cli"
brew "eza"
brew "libyaml"
brew "ruby"
brew "fastlane"
brew "gdbm"
brew "gh"
brew "git"
brew "git-lfs"
brew "go"
brew "harfbuzz"
brew "gradle"
brew "kotlin"
brew "kubeseal"
brew "kustomize"
brew "lazygit"
brew "luarocks"
brew "maclaunch"
brew "mas"
brew "neovim"
brew "nvm"
brew "pnpm"
brew "ruff"
brew "starship"
brew "stow"
brew "thefuck"
brew "watchman"
brew "zsh-syntax-highlighting"
cask "1password-cli"
cask "adobe-creative-cloud"
cask "android-studio", args: { appdir: "/Applications" }
cask "arc"
cask "bruno", args: { appdir: "/Applications" }
cask "citrix-workspace", args: { appdir: "/Applications" }
cask "clion", args: { appdir: "/Applications" }
cask "discord", args: { appdir: "/Applications" }
cask "docker", args: { appdir: "/Applications" }
cask "figma", args: { appdir: "/Applications" }
cask "intellij-idea", args: { appdir: "/Applications" }
cask "iterm2", args: { appdir: "/Applications" }
cask "keepassxc"
cask "macupdater", args: { appdir: "/Applications" }
cask "miniconda"
cask "monitorcontrol", args: { appdir: "/Applications" }
cask "notion", args: { appdir: "/Applications" }
cask "obsidian", args: { appdir: "/Applications" }
cask "pika", args: { appdir: "/Applications" }
cask "pycharm", args: { appdir: "/Applications" }
cask "sf-symbols", args: { appdir: "/Applications" }
cask "sirimote", args: { appdir: "/Applications" }
cask "spotify", args: { appdir: "/Applications" }
cask "utm"
cask "whatsapp"
cask "zulu-jdk17"
cask "zulu-jdk21", args: { appdir: "/Applications" }
mas "1Password for Safari", id: 1569813296
mas "AdGuard for Safari", id: 1440147259
mas "Goodnotes", id: 1444383602
mas "Keynote", id: 409183694
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "TestFlight", id: 899247664
mas "Xcode", id: 497799835
vscode "antfu.file-nesting"
vscode "christian-kohler.npm-intellisense"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "fivem-vscode.fivem-vscode"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.github-vscode-theme"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "hediet.vscode-drawio"
vscode "jock.svg"
vscode "ms-ceintl.vscode-language-pack-de"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode.test-adapter-converter"
vscode "ms-vscode.vscode-speech"
vscode "ms-vsliveshare.vsliveshare"
vscode "redhat.vscode-yaml"
vscode "sonarsource.sonarlint-vscode"
vscode "tomoki1207.pdf"
vscode "unifiedjs.vscode-mdx"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscode-icons-team.vscode-icons"
vscode "yinfei.luahelper"
