tap "ariga/tap"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "majd/repo"
tap "mdogan/zulu"
brew "automake"
brew "azure-cli"
brew "libyaml"
brew "ruby"
brew "cocoapods"
brew "eza"
brew "fastlane"
brew "gdbm"
brew "git"
brew "git-lfs"
brew "go"
brew "harfbuzz"
brew "gradle"
brew "graphviz"
brew "jenv"
brew "kotlin"
brew "kubeseal"
brew "kustomize"
brew "luarocks"
brew "maclaunch"
brew "mas"
brew "neovim"
brew "nvm"
brew "pnpm"
brew "pre-commit"
brew "pstree"
brew "ruff"
brew "starship"
brew "stow"
brew "watchman"
brew "yarn"
brew "zsh-syntax-highlighting"
brew "ariga/tap/atlas"
cask "adobe-creative-cloud"
cask "android-studio", args: { appdir: "/Applications" }
cask "bruno", args: { appdir: "/Applications" }
cask "citrix-workspace", args: { appdir: "/Applications" }
cask "clickup"
cask "discord", args: { appdir: "/Applications" }
cask "docker", args: { appdir: "/Applications" }
cask "figma", args: { appdir: "/Applications" }
cask "intellij-idea", args: { appdir: "/Applications" }
cask "iterm2", args: { appdir: "/Applications" }
cask "keepassxc"
cask "macupdater", args: { appdir: "/Applications" }
cask "miniconda"
cask "monitorcontrol", args: { appdir: "/Applications" }
cask "notion", args: { appdir: "/Applications" }
cask "obsidian"
cask "sf-symbols", args: { appdir: "/Applications" }
cask "sirimote", args: { appdir: "/Applications" }
cask "spotify", args: { appdir: "/Applications" }
cask "whatsapp"
cask "zulu-jdk17"
cask "zulu-jdk21"
mas "AdGuard for Safari", id: 1440147259
mas "Goodnotes", id: 1444383602
mas "Keynote", id: 409183694
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "TestFlight", id: 899247664
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
vscode "antfu.file-nesting"
vscode "bierner.markdown-mermaid"
vscode "catppuccin.catppuccin-vsc-icons"
vscode "christian-kohler.npm-intellisense"
vscode "dbaeumer.vscode-eslint"
vscode "donjayamanne.vscode-default-python-kernel"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "firsttris.vscode-jest-runner"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.github-vscode-theme"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "graphql.vscode-graphql"
vscode "graphql.vscode-graphql-syntax"
vscode "jock.svg"
vscode "meta.relay"
vscode "ms-ceintl.vscode-language-pack-de"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode.test-adapter-converter"
vscode "ms-vsliveshare.vsliveshare"
vscode "redhat.vscode-yaml"
vscode "sonarsource.sonarlint-vscode"
vscode "swmansion.react-native-ide"
vscode "tamasfe.even-better-toml"
vscode "tomoki1207.pdf"
vscode "unifiedjs.vscode-mdx"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "yinfei.luahelper"
